<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_577e8b4b312b4',
	'title' => 'Menus',
	'fields' => array (
		array (
			'key' => 'field_577e948264d3a',
			'label' => 'Menu Sections',
			'name' => 'menu_sections',
			'type' => 'flexible_content',
			'instructions' => 'Add top-level sections to this menu, e.g. "Brunch"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '577e94b3888c6',
					'name' => 'standard',
					'label' => 'Standard',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_577e953a64d3b',
							'label' => 'Section Name',
							'name' => 'section_name',
							'type' => 'text',
							'instructions' => 'e.g. "Brunch"',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_577e954664d3c',
							'label' => 'Section Description',
							'name' => 'section_description',
							'type' => 'textarea',
							'instructions' => 'e.g. "Available from 10 a.m. to 4 p.m."',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_577e8b5fab03c',
							'label' => 'Menu Items',
							'name' => 'menu_items',
							'type' => 'repeater',
							'instructions' => 'Menu items to appear under this section directly, with no subsection. ',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Item',
							'sub_fields' => array (
								array (
									'key' => 'field_577e8b6cab03d',
									'label' => 'Name',
									'name' => 'name',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 30,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_577e8b71ab03e',
									'label' => 'Description',
									'name' => 'description',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_577e8b80ab03f',
									'label' => 'Price',
									'name' => 'price',
									'type' => 'text',
									'instructions' => 'Include dollar signs if necessary. ',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 20,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5783f04e10cd8',
					'name' => 'standard_subsections',
					'label' => 'Standard with Subsections',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5783f04e10cd9',
							'label' => 'Section Name',
							'name' => 'section_name',
							'type' => 'text',
							'instructions' => 'e.g. "Brunch"',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5783f04e10cda',
							'label' => 'Section Description',
							'name' => 'section_description',
							'type' => 'textarea',
							'instructions' => 'e.g. "Available from 10 a.m. to 4 p.m."',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5783f04e10cdb',
							'label' => 'Menu Items (No Subsection)',
							'name' => 'menu_items',
							'type' => 'repeater',
							'instructions' => 'Menu items to appear under this section directly, with no subsection. ',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Item',
							'sub_fields' => array (
								array (
									'key' => 'field_5783f04e10cdc',
									'label' => 'Name',
									'name' => 'name',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 30,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5783f04e10cdd',
									'label' => 'Description',
									'name' => 'description',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5783f04e10cde',
									'label' => 'Price',
									'name' => 'price',
									'type' => 'text',
									'instructions' => 'Include dollar signs if necessary. ',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 20,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
						array (
							'key' => 'field_5783f04e10cdf',
							'label' => 'Subsections',
							'name' => 'subsections',
							'type' => 'repeater',
							'instructions' => 'Add subsections (e.g. "Sandwiches", "Desserts") to this menu section. ',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Subsection',
							'sub_fields' => array (
								array (
									'key' => 'field_5783f04e10ce0',
									'label' => 'Subsection Name',
									'name' => 'subsection_name',
									'type' => 'text',
									'instructions' => 'e.g. "Sandwiches"',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5783f04e10ce1',
									'label' => 'Subsection Description',
									'name' => 'subsection_description',
									'type' => 'textarea',
									'instructions' => 'e.g. "All sandwiches come with a side of chips or fries"',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5783f04e10ce2',
									'label' => 'Subsection Menu Items',
									'name' => 'subsection_menu_items',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => '',
									'max' => '',
									'layout' => 'table',
									'button_label' => 'Add Item',
									'sub_fields' => array (
										array (
											'key' => 'field_5783f04e10ce3',
											'label' => 'Name',
											'name' => 'name',
											'type' => 'text',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 30,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_5783f04e10ce4',
											'label' => 'Description',
											'name' => 'description',
											'type' => 'textarea',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 50,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => 2,
											'new_lines' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_5783f04e10ce5',
											'label' => 'Price',
											'name' => 'price',
											'type' => 'text',
											'instructions' => 'Include dollar signs if necessary. ',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 20,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'madwell-menu',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;